# Generated by Django 5.1.7 on 2025-10-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='1-based position inside the exam.', null=True),
        ),
    ]
