# Generated by Django 5.1.7 on 2025-11-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nclexrnreport_nclexrnattempt_nclexrnbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='nclexexam',
            name='isfree',
            field=models.BooleanField(default=False),
        ),
    ]
