# Generated by Django 5.1.7 on 2025-11-16 12:23

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pdf_delete_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paypal_order_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='api.pdf')),
            ],
            options={
                'db_table': 'api_pdf_purchase',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.pdf')),
            ],
            options={
                'db_table': 'api_purchase_session',
                'ordering': ('-created_at',),
            },
        ),
    ]
