# Generated by Django 5.1.7 on 2025-10-11 07:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('ATI_TEAS_7', 'ATI TEAS 7'), ('HESI_A2', 'HESI A2'), ('NCLEX', 'NCLEX'), ('NURSING_TEST_BANK', 'Nursing Test Bank'), ('EXIT_EXAM', 'Exit Exam')], max_length=32)),
                ('duration_days', models.PositiveSmallIntegerField(choices=[(30, '30 Days Access'), (60, '60 Days Access'), (90, '90 Days Access')])),
                ('title', models.CharField(help_text="Human friendly plan title (e.g. '30 Days Access')", max_length=180)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in smallest currency unit (e.g. dollars).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', help_text='ISO currency code', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='api.feature')),
            ],
            options={
                'ordering': ['exam_type', 'duration_days'],
                'unique_together': {('exam_type', 'duration_days')},
            },
        ),
    ]
