# Generated by Django 5.1.7 on 2025-11-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_announcementseen_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nclexquestion',
            name='format',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Format 1'), (2, 'Format 2'), (3, 'Format 3'), (4, 'Format 4'), (5, 'Format 5'), (6, 'Format 6'), (7, 'Format 7'), (8, 'Format 8'), (9, 'Format 9'), (10, 'Format 10'), (11, 'Format 11')]),
        ),
    ]
