# Generated by Django 5.1.7 on 2025-11-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pdfpurchase_purchasesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='category',
            field=models.CharField(choices=[('ATI TEAS', 'ATI TEAS'), ('NCLEX', 'NCLEX'), ('EXIT EXAMS', 'EXIT EXAMS'), ('HESI A2', 'HESI A2'), ('NURSING TESTBANK', 'NURSING TESTBANK')], default='ATI TEAS', max_length=32),
        ),
        migrations.AddField(
            model_name='pdf',
            name='proof_image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
