# Generated by Django 5.1.7 on 2025-11-24 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_nclexquestion_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCLEXPNExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isfree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NCLEXPNChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=8, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('correct_order', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_pn', to='api.nclexquestion')),
            ],
        ),
        migrations.CreateModel(
            name='NCLEXPNQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.PositiveSmallIntegerField(choices=[(1, 'Format 1'), (2, 'Format 2'), (3, 'Format 3'), (4, 'Format 4'), (5, 'Format 5'), (6, 'Format 6'), (7, 'Format 7'), (8, 'Format 8'), (9, 'Format 9'), (10, 'Format 10'), (11, 'Format 11')])),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('blank_answer', models.TextField(blank=True, null=True)),
                ('heading1', models.CharField(blank=True, max_length=255, null=True)),
                ('heading2', models.CharField(blank=True, max_length=255, null=True)),
                ('heading3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_pn', to='api.nclexpnexam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NCLEXPNPotentialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potentials_pn', to='api.nclexpnquestion')),
            ],
            options={
                'db_table': 'api_nclexpn_potentialcondition',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NCLEXPNParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_pn', to='api.nclexpnquestion')),
            ],
            options={
                'db_table': 'api_nclexpn_parameter',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NCLEXPNCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('case_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_pn', to='api.nclexpnquestion')),
            ],
        ),
        migrations.CreateModel(
            name='NCLEXPNAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_pn', to='api.nclexpnquestion')),
            ],
            options={
                'db_table': 'api_nclexpn_action',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NclexpnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nclexpn_reports', to='api.nclexpnexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nclexpn_reports', to='api.nclexpnquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nclexpn_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NclexpnAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('last_question_order', models.IntegerField(default=0)),
                ('selected_choices', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nclexpn_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nclexrpn_attempts', to='api.nclexpnexam')),
            ],
            options={
                'ordering': ('-started_at',),
                'unique_together': {('user', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='NclexpnBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nclexpn_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nclexpn_bookmarks', to='api.nclexpnexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nclexpn_bookmarks', to='api.nclexpnquestion')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
