# Generated by Django 5.1.7 on 2025-11-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_nclexpnexam_nclexpnchoice_nclexpnquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nclexpnchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_pn', to='api.nclexpnquestion'),
        ),
    ]
