# Generated by Django 5.1.7 on 2025-11-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_nclexpnchoice_question'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nclexpnattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nclexpnattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nclexpnattempt',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='nclexpnbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nclexpnbookmark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nclexpnbookmark',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nclexpnbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nclexpncase',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nclexpnchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nclexpnquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nclexpnreport',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nclexpnparameter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nclexpnpotentialcondition',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nclexpnreport',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nclexpnreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='NCLEXPNAction',
        ),
        migrations.DeleteModel(
            name='NclexpnAttempt',
        ),
        migrations.DeleteModel(
            name='NclexpnBookmark',
        ),
        migrations.DeleteModel(
            name='NCLEXPNCase',
        ),
        migrations.DeleteModel(
            name='NCLEXPNChoice',
        ),
        migrations.DeleteModel(
            name='NCLEXPNExam',
        ),
        migrations.DeleteModel(
            name='NCLEXPNParameter',
        ),
        migrations.DeleteModel(
            name='NCLEXPNPotentialCondition',
        ),
        migrations.DeleteModel(
            name='NCLEXPNQuestion',
        ),
        migrations.DeleteModel(
            name='NclexpnReport',
        ),
    ]
