# Generated by Django 5.1.7 on 2025-11-24 15:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_nclexpnattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextGenExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isfree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NextGenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.PositiveSmallIntegerField(choices=[(1, 'Format 1'), (2, 'Format 2'), (3, 'Format 3'), (4, 'Format 4'), (5, 'Format 5'), (6, 'Format 6'), (7, 'Format 7'), (8, 'Format 8'), (9, 'Format 9'), (10, 'Format 10'), (11, 'Format 11')])),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('blank_answer', models.TextField(blank=True, null=True)),
                ('heading1', models.CharField(blank=True, max_length=255, null=True)),
                ('heading2', models.CharField(blank=True, max_length=255, null=True)),
                ('heading3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_questions', to='api.nextgenexam')),
            ],
            options={
                'db_table': 'nextgen_question',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NextGenPotentialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_potentials', to='api.nextgenquestion')),
            ],
            options={
                'db_table': 'nextgen_potentialcondition',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NextGenParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_parameters', to='api.nextgenquestion')),
            ],
            options={
                'db_table': 'nextgen_parameter',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NextGenChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=8, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('correct_order', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_choices', to='api.nextgenquestion')),
            ],
            options={
                'db_table': 'nextgen_choice',
            },
        ),
        migrations.CreateModel(
            name='NextGenCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('case_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_cases', to='api.nextgenquestion')),
            ],
            options={
                'db_table': 'nextgen_case',
            },
        ),
        migrations.CreateModel(
            name='NextGenAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_actions', to='api.nextgenquestion')),
            ],
            options={
                'db_table': 'nextgen_action',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NextGenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_reports', to='api.nextgenexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_reports', to='api.nextgenquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nextgen_report',
            },
        ),
        migrations.CreateModel(
            name='NextGenAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('last_question_order', models.IntegerField(default=0)),
                ('selected_choices', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_attempts', to='api.nextgenexam')),
            ],
            options={
                'db_table': 'nextgen_attempt',
                'ordering': ('-started_at',),
                'unique_together': {('user', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='NextGenBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_bookmarks', to='api.nextgenexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextgen_bookmarks', to='api.nextgenquestion')),
            ],
            options={
                'db_table': 'nextgen_bookmark',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
