# Generated by Django 5.1.7 on 2025-10-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subscription_delete_subsciptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HesiChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('index', models.PositiveSmallIntegerField(help_text='1..6 position for this choice within the question.')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='HesiExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('total_questions', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HesiQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, help_text='1-based position inside the exam.', null=True)),
                ('format', models.PositiveSmallIntegerField(choices=[(1, 'Q, Choices, Explanation, Correct'), (2, 'Paragraph, ImagePath, Q, Choices, Explanation, Correct'), (3, 'Paragraph, Q, Choices, Explanation, Correct'), (4, 'Q, Choices, ImagePath, Explanation, Correct')])),
                ('paragraph', models.TextField(blank=True, default='')),
                ('image_path', models.CharField(blank=True, default='', max_length=1024)),
                ('question_text', models.TextField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('correct_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_correct_for', to='api.hesichoice')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.hesiexam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='hesichoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.hesiquestion'),
        ),
        migrations.AddIndex(
            model_name='hesiquestion',
            index=models.Index(fields=['exam', 'order'], name='api_hesique_exam_id_845839_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hesiquestion',
            unique_together={('exam', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='hesichoice',
            unique_together={('question', 'index')},
        ),
    ]
