# Generated by Django 5.1.7 on 2025-11-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_nextgenexam_nextgenquestion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nextgenattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nextgenattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nextgenattempt',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='nextgenbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nextgenbookmark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nextgenbookmark',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nextgenbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nextgencase',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nextgenchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nextgenquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nextgenreport',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nextgenparameter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nextgenpotentialcondition',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nextgenreport',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nextgenreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='NextGenAction',
        ),
        migrations.DeleteModel(
            name='NextGenAttempt',
        ),
        migrations.DeleteModel(
            name='NextGenBookmark',
        ),
        migrations.DeleteModel(
            name='NextGenCase',
        ),
        migrations.DeleteModel(
            name='NextGenChoice',
        ),
        migrations.DeleteModel(
            name='NextGenExam',
        ),
        migrations.DeleteModel(
            name='NextGenParameter',
        ),
        migrations.DeleteModel(
            name='NextGenPotentialCondition',
        ),
        migrations.DeleteModel(
            name='NextGenQuestion',
        ),
        migrations.DeleteModel(
            name='NextGenReport',
        ),
    ]
