# Generated by Django 5.1.7 on 2025-11-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_altnclexexam_altnclexquestion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='altbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='altbookmark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='altbookmark',
            name='question',
        ),
        migrations.RemoveField(
            model_name='altbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='altnclexaction',
            name='question',
        ),
        migrations.RemoveField(
            model_name='altnclexcase',
            name='question',
        ),
        migrations.RemoveField(
            model_name='altnclexchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='altnclexquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='altreport',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='altnclexparameter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='altnclexpotentialcondition',
            name='question',
        ),
        migrations.RemoveField(
            model_name='altreport',
            name='question',
        ),
        migrations.RemoveField(
            model_name='altreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='AltAttempt',
        ),
        migrations.DeleteModel(
            name='AltBookmark',
        ),
        migrations.DeleteModel(
            name='AltNCLEXAction',
        ),
        migrations.DeleteModel(
            name='AltNCLEXCase',
        ),
        migrations.DeleteModel(
            name='AltNCLEXChoice',
        ),
        migrations.DeleteModel(
            name='AltNCLEXExam',
        ),
        migrations.DeleteModel(
            name='AltNCLEXParameter',
        ),
        migrations.DeleteModel(
            name='AltNCLEXPotentialCondition',
        ),
        migrations.DeleteModel(
            name='AltNCLEXQuestion',
        ),
        migrations.DeleteModel(
            name='AltReport',
        ),
    ]
