# Generated by Django 5.1.7 on 2025-11-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rnlexexam_rnlexquestion_rnlexpotentialcondition_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rnlexattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rnlexattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='rnlexattempt',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rnlexbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rnlexbookmark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='rnlexbookmark',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rnlexbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rnlexcase',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rnlexchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rnlexquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='rnlexreport',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='rnlexparameter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rnlexpotentialcondition',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rnlexreport',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rnlexreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='RNLEXAction',
        ),
        migrations.DeleteModel(
            name='RnlexAttempt',
        ),
        migrations.DeleteModel(
            name='RnlexBookmark',
        ),
        migrations.DeleteModel(
            name='RNLEXCase',
        ),
        migrations.DeleteModel(
            name='RNLEXChoice',
        ),
        migrations.DeleteModel(
            name='RNLEXExam',
        ),
        migrations.DeleteModel(
            name='RNLEXParameter',
        ),
        migrations.DeleteModel(
            name='RNLEXPotentialCondition',
        ),
        migrations.DeleteModel(
            name='RNLEXQuestion',
        ),
        migrations.DeleteModel(
            name='RnlexReport',
        ),
    ]
