# Generated by Django 5.1.7 on 2025-11-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_proexam_alter_rnattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='proattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='proattempt',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='probookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='probookmark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='probookmark',
            name='question',
        ),
        migrations.RemoveField(
            model_name='probookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='procase',
            name='question',
        ),
        migrations.RemoveField(
            model_name='prochoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='proquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='proreport',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='proparameter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='propotentialcondition',
            name='question',
        ),
        migrations.RemoveField(
            model_name='proreport',
            name='question',
        ),
        migrations.RemoveField(
            model_name='proreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProAction',
        ),
        migrations.DeleteModel(
            name='ProAttempt',
        ),
        migrations.DeleteModel(
            name='ProBookmark',
        ),
        migrations.DeleteModel(
            name='ProCase',
        ),
        migrations.DeleteModel(
            name='ProChoice',
        ),
        migrations.DeleteModel(
            name='ProExam',
        ),
        migrations.DeleteModel(
            name='ProParameter',
        ),
        migrations.DeleteModel(
            name='ProPotentialCondition',
        ),
        migrations.DeleteModel(
            name='ProQuestion',
        ),
        migrations.DeleteModel(
            name='ProReport',
        ),
    ]
