# Generated by Django 5.1.7 on 2025-11-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_nursingrnatiexam_nursingrnatiquestion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nursingrnatiattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nursingrnatiattempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nursingrnatiattempt',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='nursingrnatibookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nursingrnatibookmark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nursingrnatibookmark',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nursingrnatibookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nursingrnaticase',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nursingrnatichoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nursingrnatiquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nursingrnatireport',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='nursingrnatiparameter',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nursingrnatipotentialcondition',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nursingrnatireport',
            name='question',
        ),
        migrations.RemoveField(
            model_name='nursingrnatireport',
            name='user',
        ),
        migrations.DeleteModel(
            name='NursingrnatiAction',
        ),
        migrations.DeleteModel(
            name='NursingrnatiAttempt',
        ),
        migrations.DeleteModel(
            name='NursingrnatiBookmark',
        ),
        migrations.DeleteModel(
            name='NursingrnatiCase',
        ),
        migrations.DeleteModel(
            name='NursingrnatiChoice',
        ),
        migrations.DeleteModel(
            name='NursingrnatiExam',
        ),
        migrations.DeleteModel(
            name='NursingrnatiParameter',
        ),
        migrations.DeleteModel(
            name='NursingrnatiPotentialCondition',
        ),
        migrations.DeleteModel(
            name='NursingrnatiQuestion',
        ),
        migrations.DeleteModel(
            name='NursingrnatiReport',
        ),
    ]
